FDTi_nodes = {'FLOi': {'type': 'input',
                       'unit': '1000 tonnes',
                       'name': 'Food losses per food group'},
              'FDKGi': {'type': 'input',
                        'unit': 'kg/capita/day',
                        'name': 'Kg food demand per day per food group'},
              'FDKCi': {'type': 'input',
                        'unit': 'kcal/capita/day',
                        'name': 'kcal food demand per day per food group'},
              'SSRi': {'type': 'variable',
                       'unit': '1',
                       'name': 'Self-sufficiency ratio per food group',
                       'computation': lambda FPi, FEi, FIi, **kwargs: FPi / (FPi - FEi + FIi)
                       },
              'FPi': {'type': 'input',
                      'unit': '1000 tonnes',
                      'name': 'Food production per food group'},
              'FEi': {'type': 'input',
                      'unit': '1000 tonnes',
                      'name': 'Food exports per food group'},
              'FIi': {'type': 'input',
                      'unit': '1000 tonnes',
                      'name': 'Food imports per food group'},
              'FDPi': {'type': 'variable',
                       'unit': '1000 tonnes',
                       'name': 'Total domestic food production per food group',
                       'computation': lambda FDKGi, P, FLOi, SSRi, **kwargs: (FDKGi * 1e-9 * 365 * P * 1e3 + FLOi) * SSRi
                       },
              'OFi': {'type': 'variable',
                      'unit': '1000 tonnes',
                      'name': 'Other food demand',
                      'computation': lambda SDi, NFDi, PDi, RDi, SVi, **kwargs: SDi + NFDi + PDi + RDi + SVi
                      },
              'SDi': {'type': 'input',
                      'unit': '1000 tonnes',
                      'name': 'Seed demand per food group'},
              'NFDi': {'type': 'input',
                       'unit': '1000 tonnes',
                       'name': 'Non-food demand per food group'},
              'PDi': {'type': 'input',
                      'unit': '1000 tonnes',
                      'name': 'Processed demand per food group'},
              'RDi': {'type': 'input',
                      'unit': '1000 tonnes',
                      'name': 'Residual demand per food group'},
              'SVi': {'type': 'input',
                      'unit': '1000 tonnes',
                      'name': 'Stock variation per food group'},
              'FDTi': {'type': 'output',
                       'name': 'Total food demand per food group',
                       'unit': '1000 tonnes',
                       'computation': lambda SSRi, OFi, FDi, FDPi, **kwargs: SSRi * (OFi + FDi) + FDPi
                       },
              'FDi': {'type': 'input',
                      'unit': '1000 tonnes',
                      'name': 'Feed demand per food group'},
              'P': {'type': 'input', 'unit': '1000 persons', 'name': 'Total population'}}
