processing_properties = {'FBS': {'path': 'FoodBalanceSheets_E_All_Data_(Normalized).csv',
                                 'elements_to_drop': ['Total Population - Both sexes',
                                                      'Fat supply quantity (g/capita/day)',
                                                      'Tourist consumption',
                                                      'Protein supply quantity (g/capita/day)'],
                                 'items_to_drop': ['Population', 'Grand Total', 'Miscellaneous'], },
                         'GE': {'path': 'Emissions_Agriculture_Enteric_Fermentation_E_All_Data_(Normalized).csv',
                                'elements_to_drop': [],
                                'items_to_drop': []},
                         'QA': {'path': 'Production_Livestock_E_All_Data_(Normalized).csv',
                                'elements_to_drop': [],
                                'items_to_drop': []},
                         'QL': {'path': 'Production_LivestockPrimary_E_All_Data_(Normalized).csv',
                                'elements_to_drop': [],
                                'items_to_drop': []},
                         'QD': {'path': 'Production_CropsProcessed_E_All_Data_(Normalized).csv',
                                'elements_to_drop': [],
                                'items_to_drop': []},
                         'QC': {'path': 'Production_Crops_E_All_Data_(Normalized).csv',
                                'elements_to_drop': [],
                                'items_to_drop': []},
                         'RL': {'path': 'Inputs_LandUse_E_All_Data_(Normalized).csv',
                                'elements_to_drop': [],
                                'items_to_drop': []},
                         'GY': {'path': 'Emissions_Agriculture_Synthetic_Fertilizers_E_All_Data_(Normalized).csv',
                                'elements_to_drop': [],
                                'items_to_drop': []},
                         'EMN': {'path': 'Environment_LivestockManure_E_All_Data_(Normalized).csv',
                                 'elements_to_drop': [],
                                 'items_to_drop': []},
                         'GP': {'path': 'Emissions_Agriculture_Manure_left_on_pasture_E_All_Data_(Normalized).csv',
                                'elements_to_drop': [],
                                'items_to_drop': []},
                         'GM': {'path': 'Emissions_Agriculture_Manure_Management_E_All_Data_(Normalized).csv',
                                'elements_to_drop': [],
                                'items_to_drop': []},
                         'GU': {'path': 'Emissions_Agriculture_Manure_applied_to_soils_E_All_Data_(Normalized).csv',
                                'elements_to_drop': [],
                                'items_to_drop': []},
                         'GT': {'path': 'Emissions_Agriculture_Agriculture_total_E_All_Data_(Normalized).csv',
                                'elements_to_drop': [],
                                'items_to_drop': []},
                         'GL': {'path': 'Emissions_Land_Use_Land_Use_Total_E_All_Data_(Normalized).csv',
                                'elements_to_drop': [],
                                'items_to_drop': []}}
